### ISSUE TITLE
 'COMMON_MYSQL_READ_ONLY_PASS' is undefined"

### ISSUE THREAD

**Issue by SalahAdDin** [OpenSaasAU/edx-docker-ansible#13]
Thank you, I overcame the previous problem, but now I have acquired another problem:
```bash
TASK [docker_db_setup : create read-only reports user for the analytics-api] ***
task path: /src/roles/docker_db_setup/tasks/main.yml:78
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/database/mysql/mysql_user.py
<7fed6b326d28f87dad6b5825e52a165d5eaea21e561fb96e4ad85b47154c78a1> ESTABLISH DOCKER CONNECTION FOR USER: root
<7fed6b326d28f87dad6b5825e52a165d5eaea21e561fb96e4ad85b47154c78a1> EXEC ['/usr/local/bin/docker', 'exec', '-i', u'7fed6b326d28f87dad6b5825e52a165d5eaea21e561fb96e4ad85b47154c78a1', u'/bin/sh', '-c', u"/bin/sh -c 'echo ~ && sleep 0'"]
<7fed6b326d28f87dad6b5825e52a165d5eaea21e561fb96e4ad85b47154c78a1> EXEC ['/usr/local/bin/docker', 'exec', '-i', u'7fed6b326d28f87dad6b5825e52a165d5eaea21e561fb96e4ad85b47154c78a1', u'/bin/sh', '-c', u'/bin/sh -c \'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1501430829.69-53889190217745 `" && echo ansible-tmp-1501430829.69-53889190217745="` echo /root/.ansible/tmp/ansible-tmp-1501430829.69-53889190217745 `" ) && sleep 0\'']
<7fed6b326d28f87dad6b5825e52a165d5eaea21e561fb96e4ad85b47154c78a1> PUT /tmp/tmpIEKSjd TO /root/.ansible/tmp/ansible-tmp-1501430829.69-53889190217745/mysql_user.py
<7fed6b326d28f87dad6b5825e52a165d5eaea21e561fb96e4ad85b47154c78a1> EXEC ['/usr/local/bin/docker', 'exec', '-i', u'7fed6b326d28f87dad6b5825e52a165d5eaea21e561fb96e4ad85b47154c78a1', u'/bin/sh', '-c', u"/bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1501430829.69-53889190217745/ /root/.ansible/tmp/ansible-tmp-1501430829.69-53889190217745/mysql_user.py && sleep 0'"]
<7fed6b326d28f87dad6b5825e52a165d5eaea21e561fb96e4ad85b47154c78a1> EXEC ['/usr/local/bin/docker', 'exec', '-i', u'7fed6b326d28f87dad6b5825e52a165d5eaea21e561fb96e4ad85b47154c78a1', u'/bin/sh', '-c', u'/bin/sh -c \'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1501430829.69-53889190217745/mysql_user.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1501430829.69-53889190217745/" > /dev/null 2>&1 && sleep 0\'']
ok: [db] => {
    "changed": false,
    "failed": false,
    "invocation": {
        "module_args": {
            "append_privs": false,
            "check_implicit_admin": false,
            "config_file": "/root/.my.cnf",
            "connect_timeout": 30,
            "encrypted": false,
            "host": "%",
            "host_all": false,
            "login_host": "localhost",
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_port": 3306,
            "login_unix_socket": null,
            "login_user": "root",
            "name": "reports001",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "priv": "reports.*:SELECT",
            "sql_log_bin": true,
            "ssl_ca": null,
            "ssl_cert": null,
            "ssl_key": null,
            "state": "present",
            "update_password": "always",
            "user": "reports001"
        }
    },
    "user": "reports001"
}

TASK [docker_db_setup : create a database for the hive metastore] **************
task path: /src/roles/docker_db_setup/tasks/main.yml:92
skipping: [db] => {
    "changed": false,
    "skip_reason": "Conditional result was False",
    "skipped": true
}

TASK [docker_db_setup : setup the edx-notes-api db user] ***********************
task path: /src/roles/docker_db_setup/tasks/main.yml:105
skipping: [db] => {
    "changed": false,
    "skip_reason": "Conditional result was False",
    "skipped": true
}

TASK [docker_db_setup : setup the read-only db user] ***************************
task path: /src/roles/docker_db_setup/tasks/main.yml:119
fatal: [db]: FAILED! => {
    "failed": true,
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined.The error was: 'COMMON_MYSQL_READ_ONLY_PASS' is undefined\n\nThe error appears to have been in '/src/roles/docker_db_setup/tasks/main.yml': line 119, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: setup the read-only db user\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'COMMON_MYSQL_READ_ONLY_PASS' is undefined"
}
	to retry, use: --limit @/tmp/tmpFtfNH_/playbook.retry

PLAY RECAP *********************************************************************
db                         : ok=7    changed=2    unreachable=0    failed=1

2017-07-30T16:07:10.323433 Error applying role!           [container.core] caller_file=/_ansible/container/core.py caller_func=apply_role_to_container caller_line=627 engine=<container.docker.engine.Engine object at 0x7f9aaab9f590> exit_code=2 playbook=[{'hosts': u'db', 'roles': [ordereddict([('DB_MYSQL_HOST', 'localhost'), ('role', 'docker_db_setup')])], 'vars': {u'DOCKER_EDX_ROOT': u'/home/salahaddin/Proyectos/Works/edx-ansible/EDX_DATASTORE/edxapp', u'EDXAPP_CMS_NGINX_PORT': 18010, u'EDXAPP_CELERY_PASSWORD': u'password', u'EDXAPP_MYSQL_DB_NAME': u'edxapp', u'XQUEUE_NGINX_PORT': 18040, u'EDXAPP_LMS_NGINX_PORT': 80, u'DOCKER_DATA_ROOT': u'/home/salahaddin/Proyectos/Works/edx-ansible/EDX_DATASTORE/edxdata', u'relax': True, u'EDXAPP_MYSQL_USER': u'edxapp001', u'COMMON_MYSQL_READ_ONLY_USER': u'read_only', u'EDXAPP_LMS_PREVIEW_NGINX_PORT': 18020, u'EDXAPP_MYSQL_PASSWORD': u'password', u'INSIGHTS_NGINX_PORT': 18110, u'ANALYTICS_API_NGINX_PORT': 18100, u'COMMON_MYSQL_MIGRATE_PASS': u'password', u'EDXAPP_CELERY_USER': u'celery'}}]
2017-07-30T16:07:10.327101 Playbook run finished.         [container.core] caller_file=/_ansible/container/core.py caller_func=conductorcmd_build caller_line=753 exit_code=2
Traceback (most recent call last):
  File "/usr/local/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 379, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 755, in conductorcmd_build
    raise RuntimeError('Build failed.')
RuntimeError: Build failed.
2017-07-30T19:07:11.524099 Conductor terminated. Cleaning up. [container.docker.engine] caller_file=/home/salahaddin/Proyectos/Works/edx-ansible/src/ansible-container/container/docker/engine.py caller_func=await_conductor_command caller_line=379 command_rc=1 conductor_id=2c3de27a1538b83f4d1ba070bc83de0b862af05d688cf14aaf113d5ff3be903a save_container=False
2017-07-30T19:07:12.199317 Conductor exited with status 1 [container.cli] caller_file=/home/salahaddin/Proyectos/Works/edx-ansible/src/ansible-container/container/cli.py caller_func=__call__ caller_line=291
```

**Comment by borisno2** [comment]
@SalahAdDin I came across the same problem and fixed it in the latest commit. So if you pull the latest version it should work.

**Comment by SalahAdDin** [comment]
@borisno2 I have other like this:
```bash
TASK [nginx : Create nginx app and data dirs] **********************************
task path: /src/roles/nginx/tasks/main.yml:4
fatal: [nginx]: FAILED! => {
    "failed": true,
    "msg": "{{ COMMON_APP_DIR }}/nginx: 'COMMON_APP_DIR' is undefined"
}
	to retry, use: --limit @/tmp/tmpXVBi9A/playbook.retry

PLAY RECAP *********************************************************************
nginx                      : ok=1    changed=0    unreachable=0    failed=1
```
