### ISSUE TITLE
Cannot start service db: oci runtime error: container_linux.go:262

### ISSUE THREAD

**Issue by SalahAdDin** [OpenSaasAU/edx-docker-ansible#15]
i'm sorry for all issues, but i have a bug running `ansible-run` in local:
```bash
PLAY [Deploy edx-docker-ansible] ***********************************************

TASK [docker_service] **********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "errors": ["ERROR: for edxdockeransible_db_1  Cannot start service db: oci runtime error: container_linux.go:262: starting container process caused \"exec: \\\"\\\": executable file not found in $PATH\"", "ERROR: for db  Cannot start service db: oci runtime error: container_linux.go:262: starting container process caused \"exec: \\\"\\\": executable file not found in $PATH\""], "failed": true, "module_stderr": "Starting edxdockeransible_mongo_1 ... \r\nStarting edxdockeransible_memcache_1 ... \r\nStarting edxdockeransible_db_1 ... \r\nStarting edxdockeransible_es_1 ... \r\nStarting edxdockeransible_rabbitmq_1 ... \r\n\r\u001b[1B\nERROR: for edxdockeransible_db_1  Cannot start service db: oci runtime error: container_linux.go:262: starting container process caused \"exec: \\\"\\\": executable file not found in $PATH\"\n\nERROR: for db  Cannot start service db: oci runtime error: container_linux.go:262: starting container process caused \"exec: \\\"\\\": executable file not found in $PATH\"\n", "module_stdout": "", "msg": "Error starting project ERROR: for db  Cannot start service db: oci runtime error: container_linux.go:262: starting container process caused \"exec: \\\"\\\": executable file not found in $PATH\""}
	to retry, use: --limit @/home/salahaddin/Proyectos/Works/edx-ansible/edx-docker-ansible/ansible-deployment/playbook.retry
, no
PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1

Traceback (most recent call last):
  File "/usr/local/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 392, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 810, in conductorcmd_run
    'Error executing the run command. Not all containers may be running.'
container.exceptions.AnsibleContainerException: Error executing the run command. Not all containers may be running.
Conductor terminated. Cleaning up.	command_rc=1 conductor_id=d5e356a554c41a7ec3d34a9c91aa921429efed70f43cca76b24ef31488260624 save_container=False
ERROR	Conductor exited with status 1	
```

I'm working in locally, not in the server and actually i didn't deploy in any server, maybe this is the problem, i'm only testing it.d

**Comment by borisno2** [comment]
@SalahAdDin Can you try the latest build and see if this error still occurs?

**Comment by SalahAdDin** [comment]
Yes, it is working, but i don't know where can i test if is working fine, i mean, which url? which port?

```bash
docker ps                                                                                        ✓  4120  01:06:34 
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS               NAMES
5976cb1a30c6        edx-docker-ansible-analytics:20170731002223   "/edx/app/supervis..."   2 hours ago         Up 38 minutes                           edxdockeransible_analytics_1
720f06fc3648        edx-docker-ansible-insights:20170731002754    "/edx/app/supervis..."   2 hours ago         Up 38 minutes                           edxdockeransible_insights_1
7cd32063b984        edx-docker-ansible-edxworker:latest           "/edx/app/supervis..."   2 hours ago         Up 38 minutes                           edxdockeransible_lms_1
e062db3a6799        edx-docker-ansible-edxworker:latest           "/edx/app/supervis..."   2 hours ago         Up 38 minutes                           edxdockeransible_edxworker_1
76838732694b        edx-docker-ansible-cms:20170731001949         "/edx/app/supervis..."   2 hours ago         Up 38 minutes                           edxdockeransible_cms_1
342821e38c25        edx-docker-ansible-forums:20170730233014      "/edx/app/supervis..."   2 hours ago         Up 38 minutes                           edxdockeransible_forums_1
f199e33ced42        edx-docker-ansible-mongo:20170730231544       "/entrypoint.sh mo..."   2 hours ago         Up 38 minutes       27017/tcp           edxdockeransible_mongo_1
1fa01d412f8a        edx-docker-ansible-es:20170730230017          "/usr/share/elasti..."   2 hours ago         Up 38 minutes                           edxdockeransible_es_1
840da1fb4e50        memcached:1.4.24                              "/entrypoint.sh me..."   2 hours ago         Up 38 minutes       11211/tcp           edxdockeransible_memcache_1
d9e70dc0d3f7        rabbitmq:3.5.3                                "/docker-entrypoin..."   2 hours ago         Up 38 minutes       5672/tcp            edxdockeransible_rabbitmq_1
```

A big problem here:
```bash
docker ps -a                                                                                     ✓  4126  01:48:07 
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS                       PORTS               NAMES
455f57dccdd4        edx-docker-ansible-nginx:20170730232218       "nginx -g 'daemon ..."   2 hours ago         Exited (1) 4 minutes ago                         edxdockeransible_nginx_1
5976cb1a30c6        edx-docker-ansible-analytics:20170731002223   "/edx/app/supervis..."   2 hours ago         Exited (0) 4 minutes ago                         edxdockeransible_analytics_1
720f06fc3648        edx-docker-ansible-insights:20170731002754    "/edx/app/supervis..."   2 hours ago         Exited (0) 4 minutes ago                         edxdockeransible_insights_1
7cd32063b984        edx-docker-ansible-edxworker:latest           "/edx/app/supervis..."   2 hours ago         Exited (0) 4 minutes ago                         edxdockeransible_lms_1
e062db3a6799        edx-docker-ansible-edxworker:latest           "/edx/app/supervis..."   2 hours ago         Exited (0) 4 minutes ago                         edxdockeransible_edxworker_1
76838732694b        edx-docker-ansible-cms:20170731001949         "/edx/app/supervis..."   2 hours ago         Exited (0) 4 minutes ago                         edxdockeransible_cms_1
342821e38c25        edx-docker-ansible-forums:20170730233014      "/edx/app/supervis..."   2 hours ago         Exited (0) 4 minutes ago                         edxdockeransible_forums_1
f199e33ced42        edx-docker-ansible-mongo:20170730231544       "/entrypoint.sh mo..."   2 hours ago         Exited (0) 3 minutes ago                         edxdockeransible_mongo_1
1fa01d412f8a        edx-docker-ansible-es:20170730230017          "/usr/share/elasti..."   2 hours ago         Exited (143) 3 minutes ago                       edxdockeransible_es_1
840da1fb4e50        memcached:1.4.24                              "/entrypoint.sh me..."   2 hours ago         Exited (0) 3 minutes ago                         edxdockeransible_memcache_1
3a06eff37ff7        edx-docker-ansible-db:20170730224915          "mysqld"                 2 hours ago         Exited (1) 4 minutes ago                         edxdockeransible_db_1
```

**Comment by SalahAdDin** [comment]
Here are the logs from the bad-exited containers:
```bash
~/Proyectos/Works/edx-ansible/edx-docker-ansible  ansible-container0.9 ● ↑4  edx-ansible  docker logs 455f57dccdd4                                                                         ✓  4131  02:41:45 
2017/08/11 21:01:50 [emerg] 1#1: unexpected "O" in /etc/nginx/sites-enabled/cms:19
nginx: [emerg] unexpected "O" in /etc/nginx/sites-enabled/cms:19
2017/08/11 21:22:06 [emerg] 1#1: unexpected "O" in /etc/nginx/sites-enabled/cms:19
nginx: [emerg] unexpected "O" in /etc/nginx/sites-enabled/cms:19
2017/08/11 21:29:38 [emerg] 1#1: unexpected "O" in /etc/nginx/sites-enabled/cms:19
nginx: [emerg] unexpected "O" in /etc/nginx/sites-enabled/cms:19
2017/08/11 21:32:46 [emerg] 1#1: unexpected "O" in /etc/nginx/sites-enabled/cms:19
nginx: [emerg] unexpected "O" in /etc/nginx/sites-enabled/cms:19
2017/08/11 21:34:43 [emerg] 1#1: unexpected "O" in /etc/nginx/sites-enabled/cms:19
nginx: [emerg] unexpected "O" in /etc/nginx/sites-enabled/cms:19
2017/08/11 21:39:21 [emerg] 1#1: unexpected "O" in /etc/nginx/sites-enabled/cms:19
nginx: [emerg] unexpected "O" in /etc/nginx/sites-enabled/cms:19
2017/08/11 22:06:29 [emerg] 1#1: unexpected "O" in /etc/nginx/sites-enabled/cms:19
nginx: [emerg] unexpected "O" in /etc/nginx/sites-enabled/cms:19
2017/08/11 22:45:35 [emerg] 1#1: unexpected "O" in /etc/nginx/sites-enabled/cms:19
nginx: [emerg] unexpected "O" in /etc/nginx/sites-enabled/cms:19
 salahaddin@TulipanROG  ~/Proyectos/Works/edx-ansible/edx-docker-ansible  ansible-container0.9 ● ↑4  edx-ansible  docker logs 3a06eff37ff7                                                                         ✓  4132  03:17:18 
2017-08-11T21:00:51.762054Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2017-08-11T21:00:52.151835Z 0 [Note] mysqld (mysqld 5.7.19) starting as process 1 ...
2017-08-11T21:00:56.375938Z 0 [ERROR] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!

2017-08-11T21:00:56.375991Z 0 [ERROR] Aborting

2017-08-11T21:00:56.782540Z 0 [Note] Binlog end
2017-08-11T21:00:56.796094Z 0 [Note] mysqld: Shutdown complete

2017-08-11T21:22:04.937719Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2017-08-11T21:22:04.939966Z 0 [Note] mysqld (mysqld 5.7.19) starting as process 1 ...
2017-08-11T21:22:05.065275Z 0 [ERROR] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!

2017-08-11T21:22:05.065311Z 0 [ERROR] Aborting

2017-08-11T21:22:05.069013Z 0 [Note] Binlog end
2017-08-11T21:22:05.093739Z 0 [Note] mysqld: Shutdown complete

2017-08-11T21:29:30.811923Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2017-08-11T21:29:30.812773Z 0 [Note] mysqld (mysqld 5.7.19) starting as process 1 ...
2017-08-11T21:29:30.813867Z 0 [ERROR] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!

2017-08-11T21:29:30.813881Z 0 [ERROR] Aborting

2017-08-11T21:29:30.813893Z 0 [Note] Binlog end
2017-08-11T21:29:30.814060Z 0 [Note] mysqld: Shutdown complete

2017-08-11T21:32:45.083689Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2017-08-11T21:32:45.084815Z 0 [Note] mysqld (mysqld 5.7.19) starting as process 1 ...
2017-08-11T21:32:45.086391Z 0 [ERROR] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!

2017-08-11T21:32:45.086414Z 0 [ERROR] Aborting

2017-08-11T21:32:45.086428Z 0 [Note] Binlog end
2017-08-11T21:32:45.087401Z 0 [Note] mysqld: Shutdown complete

2017-08-11T21:34:37.468662Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2017-08-11T21:34:37.469586Z 0 [Note] mysqld (mysqld 5.7.19) starting as process 1 ...
2017-08-11T21:34:37.470814Z 0 [ERROR] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!

2017-08-11T21:34:37.470831Z 0 [ERROR] Aborting

2017-08-11T21:34:37.470843Z 0 [Note] Binlog end
2017-08-11T21:34:37.471022Z 0 [Note] mysqld: Shutdown complete

2017-08-11T21:39:19.538230Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2017-08-11T21:39:19.540411Z 0 [Note] mysqld (mysqld 5.7.19) starting as process 1 ...
2017-08-11T21:39:19.687926Z 0 [ERROR] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!

2017-08-11T21:39:19.687955Z 0 [ERROR] Aborting

2017-08-11T21:39:19.691738Z 0 [Note] Binlog end
2017-08-11T21:39:19.716451Z 0 [Note] mysqld: Shutdown complete

2017-08-11T22:06:15.118898Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2017-08-11T22:06:15.127171Z 0 [Note] mysqld (mysqld 5.7.19) starting as process 1 ...
2017-08-11T22:06:15.128611Z 0 [ERROR] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!

2017-08-11T22:06:15.128639Z 0 [ERROR] Aborting

2017-08-11T22:06:15.128663Z 0 [Note] Binlog end
2017-08-11T22:06:15.129923Z 0 [Note] mysqld: Shutdown complete

2017-08-11T22:45:33.898433Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2017-08-11T22:45:33.917778Z 0 [Note] mysqld (mysqld 5.7.19) starting as process 1 ...
2017-08-11T22:45:34.103788Z 0 [ERROR] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!

2017-08-11T22:45:34.103831Z 0 [ERROR] Aborting

2017-08-11T22:45:34.107565Z 0 [Note] Binlog end
2017-08-11T22:45:34.121119Z 0 [Note] mysqld: Shutdown complete
```

**Comment by SalahAdDin** [comment]
@borisno2 Is there still nothing?

**Comment by borisno2** [comment]
@SalahAdDin Try the latest commit... you will need to do a new build. Let me know how it goes.
