### ISSUE TITLE
ValueError: Extra data: line 2 column 1 - line 3 column 1 (char 730 - 1470)

### ISSUE THREAD

**Issue by natea** [OpenSaasAU/edx-docker-ansible#5]
This doesn't seem to be a problem with your code, but I noticed it when running ansible-build:

```
ansible-container_1  | PLAY [es,edxconfig,lms,cms,edxworker,xqueue,analytics,forums,insights] *********
ansible-container_1  |
ansible-container_1  | TASK [raw] *********************************************************************
Exception in thread Thread-35:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/nateaune/Dropbox/code/edx-docker-ansible/ansible-container/lib/python2.7/site-packages/compose/cli/log_printer.py", line 190, in watch_events
    for event in event_stream:
  File "/Users/nateaune/Dropbox/code/edx-docker-ansible/ansible-container/lib/python2.7/site-packages/compose/project.py", line 343, in events
    decode=True
  File "/Users/nateaune/Dropbox/code/edx-docker-ansible/ansible-container/lib/python2.7/site-packages/docker/client.py", line 233, in _stream_helper
    data = json.loads(data)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 3 column 1 (char 730 - 1470)
```

**Comment by borisno2** [comment]
Shouldn't be an issue with the latest ansible-container
