### ISSUE TITLE
docker.errors.APIError: 500 Server Error: Internal Server Error ( only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed)

### ISSUE THREAD

**Issue by SalahAdDin** [OpenSaasAU/edx-docker-ansible#9]
Testing the new branch for `0.9.1` i got this problem.

```bash
Traceback (most recent call last):
  File "/usr/local/bin/conductor", line 11, in <module>
    load_entry_point('ansible-container', 'console_scripts', 'conductor')()
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/cli.py", line 378, in conductor_commandline
    **params)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/core.py", line 736, in conductorcmd_build
    container_id = engine.run_container(cur_image_id, service_name, **run_kwargs)
  File "/_ansible/container/docker/engine.py", line 83, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/_ansible/container/__init__.py", line 19, in __wrapped__
    return fn(*args, **kwargs)
  File "/_ansible/container/docker/engine.py", line 202, in run_container
    **run_kwargs
  File "/usr/local/lib/python2.7/dist-packages/docker/models/containers.py", line 697, in run
    detach=detach, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/models/containers.py", line 741, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 447, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 458, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 226, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 222, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("create ~/Proyectos/Works/openedx-ansible/edx-docker-ansible/data/mysql/data: "~/Proyectos/Works/openedx-ansible/edx-docker-ansible/data/mysql/data" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path")
2017-07-11T01:35:36.687464 Conductor terminated. Cleaning up. [container.docker.engine] caller_file=/home/salahaddin/Proyectos/Works/text-ansible-container/ansible-container/container/docker/engine.py caller_func=await_conductor_command caller_line=356 command_rc=1 conductor_id=be1b475eb407777b99fdb59ca4f70a1c0579d6e22f64bb21e6895c3f10f39705 save_container=False
2017-07-11T01:35:37.166254 Conductor exited with status 1 [container.cli] caller_file=/home/salahaddin/Proyectos/Works/text-ansible-container/ansible-container/container/cli.py caller_func=__call__ caller_line=290
```

What's the problem?

**Comment by SalahAdDin** [comment]
Is solved putting the full path instead `~` in the container variables.
